@url = https://8080-danilozanet-gamessw2202-5g94wtxte94.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "Play"
}

###
GET {{url}}/plataformas/2